// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const getSupabaseAuthStorage = () => sessionStorage;

const getSupabaseProjectRef = () => {
  try {
    return new URL(SUPABASE_URL).hostname.split(".")[0] || "";
  } catch {
    return "";
  }
};

export const readPersistedSupabaseSession = () => {
  if (typeof window === "undefined") return null;
  try {
    const storage = getSupabaseAuthStorage();
    const projectRef = getSupabaseProjectRef();
    const explicitKey = projectRef ? `sb-${projectRef}-auth-token` : "";
    const candidateKeys = explicitKey
      ? [explicitKey]
      : Object.keys(storage).filter((key) => key.startsWith("sb-") && key.endsWith("-auth-token"));

    for (const key of candidateKeys) {
      const raw = storage.getItem(key);
      if (!raw) continue;
      const parsed = JSON.parse(raw);
      if (parsed?.user && parsed?.access_token) return parsed;
      if (parsed?.currentSession?.user && parsed?.currentSession?.access_token) return parsed.currentSession;
      if (Array.isArray(parsed)) {
        for (const item of parsed) {
          if (item?.user && item?.access_token) return item;
          if (item?.currentSession?.user && item?.currentSession?.access_token) return item.currentSession;
        }
      }
    }
  } catch {
    // ignore storage parsing issues
  }
  return null;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSupabaseAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
